services:
  db:
    image: postgres:16.0-alpine
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "16872:5432"
    networks:
      - app_network
    env_file:
      - ./.env.config_compose

  web:
    image: denisshahbazyan/fastapi_proxy:latest  # TODO: Для продакшена заменить на свой образ
    environment:
      - ENVIRONMENT=docker
    container_name: fastapi
    restart: always
    depends_on:
      - db
    expose:
      - "8000"
    networks:
      - app_network
    env_file:
      - .env.docker

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/start.sh:/start.sh
      - nginx_certs:/etc/nginx/certs
      - nginx_webroot:/usr/share/nginx/html
    entrypoint: ["/bin/sh", "/start.sh"]
    depends_on:
      - web
    networks:
      - app_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - nginx_certs:/etc/letsencrypt
      - nginx_lib_certs:/var/lib/letsencrypt
      - nginx_webroot:/usr/share/nginx/html
    networks:
      - app_network
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h; done"

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  nginx_certs:
  nginx_lib_certs:
  nginx_webroot:
