services:
  db:
    image: postgres:18.0-alpine
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "16872:5432"
    networks:
      - app_network
    env_file:
      - .env.docker

  web:
    build: .
    container_name: fastapi
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app_network
    env_file:
      - .env.docker

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
