##########################################
#                PreCommit               #
##########################################
[tool.autoflake]
in-place = true
remove-all-unused-imports = true
ignore-init-module-imports = true

[tool.isort]
profile = "black"
skip_glob = [
    "__pycache__/*",
    "venv/*",
    "alembic/*",
    "app/api/endpoints/__init__.py",
    "app/core/base.py",
    "app/models/__init__.py",
]

[tool.black]
line-length = 88
skip-string-normalization = true

[tool.flake8]
max-line-length = 88
ignore = ["F821", "W503", "E701"]
exclude = [
    "__pycache__/*",
    "venv/*",
    "alembic/*",
    "app/api/endpoints/__init__.py",
    "app/core/base.py",
    "app/models/__init__.py",
]

[tool.ruff]
exclude = [
    "__pycache__/*",
    "venv/*",
    "alembic/*",
    "app/api/endpoints/__init__.py",
    "app/core/base.py",
    "app/models/__init__.py",
]
lint.select = ["E", "W", "F", "C", "N"]
lint.ignore = ["F821"]
line-length = 88


##########################################
#                  MyPy                  #
##########################################
[tool.mypy]
python_version = "3.13"
mypy_path = "$MYPY_CONFIG_FILE_DIR/app/"

exclude = ["alembic/*", "venv/*"]
plugins = ["pydantic.mypy"]

strict = true


##########################################
#                 PyTest                 #
##########################################
[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
testpaths = ["tests"]
pythonpath = [".", "app"]
filterwarnings = ["ignore::DeprecationWarning"]


##########################################
#                   UV                   #
##########################################
[project]
name = "fastapi-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "alembic>=1.15.2",
    "asyncpg>=0.30.0",
    "fastapi-users[sqlalchemy]>=14.0.1",
    "fastapi[standard]>=0.115.12",
    "gunicorn>=23.0.0",
    "orjson>=3.10.16",
    "pydantic-settings>=2.8.1",
    "sqlalchemy>=2.0.40",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "flake8>=7.2.0",
    "flake8-pyproject>=1.2.3",
    "mypy>=1.16.1",
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
]
